import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Links } from "./components/Links";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Education Jobs",
  description: "Generated by ayushballia",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Links />
        {children}
      </body>
    </html>
  );
}
